### ISSUE TITLE
Could not compile dotenv

### ISSUE THREAD

**Issue by jansel369** [dotenv-rs/dotenv#21]
------Terminal Display------
```bash
(base) [jansel@jansel-pc zzz]$ cargo build
   Compiling dotenv v0.10.1
   Compiling failure_derive v0.1.5
   Compiling serde v1.0.92
   Compiling diesel v1.4.2
error[E0659]: `error_chain` is ambiguous (derive helper attribute vs any other name)
  --> /home/jansel/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:23:40
   |
23 | #[cfg_attr(not(feature = "backtrace"), error_chain(backtrace = "false"))]
   |                                        ^^^^^^^^^^^ ambiguous name
   |
note: `error_chain` could refer to the derive helper attribute defined here
  --> /home/jansel/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:22:17
   |
22 | #[derive(Debug, error_chain)]
   |                 ^^^^^^^^^^^
note: `error_chain` could also refer to the derive macro imported here
  --> /home/jansel/.cargo/registry/src/github.com-1ecc6299db9ec823/dotenv-0.10.1/src/lib.rs:10:1
   |
10 | #[macro_use]
   | ^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0659`.
error: Could not compile `dotenv`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
---My dependencies---

actix = "0.8"
actix-rt = "0.2"
actix-web = "1.0.0"
env_logger = "0.6"
openssl = { version="0.10" }
mime = "0.3"
postgres = "0.15"
juniper = "0.12"
diesel = { version = "1.4", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.14.1"

**Comment by dgriffen** [comment]
Can you also post what rust version you have and what edition you are compiling for? I'll see if I can repro but unfortunately I don't have permission to patch previous versions of dotenv. @sgrif if I can reproduce this and make a patch for the `v0.10.x` branch would you be willing to review it and let me publish that?

**Comment by sgrif** [comment]
Yes

**Comment by jansel369** [comment]
--- rustc version --
```bash
rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
```
The problem seems to be from my diesel_codegen-0.16 dependency of dotenv-0.10.1. My dotenv-0.14.1 display no error from the independent build.

**Comment by sgrif** [comment]
For the record, `diesel_codegen` was removed a very long time ago and there's no reason to be using it with Diesel 1.0

**Comment by jansel369** [comment]
I must be using an old reference, thanks anyway.
