### ISSUE TITLE
Trait std::error::Error not implemented for dotenv::errors::Error

### ISSUE THREAD

**Issue by mkeedlinger** [dotenv-rs/dotenv#23]
*Much the same issue as [here](https://github.com/jgallagher/amiquip/issues/10), but I'll put info here for simplicity.*

[Error is a trait](https://doc.rust-lang.org/std/error/trait.Error.html) that "[represents] the basic expectations for error values".

It should be easy to implement, the problem is that your implementation of `failure::Fail` conflicts because of the `cause` function. I was hoping there might be an updated version of `failure` that had fixed the issue and you could simply upgrade, but sadly the most recent version<sup>1</sup> [still has the collision](https://docs.rs/failure/0.1.5/failure/trait.Fail.html#provided-methods).

1: Version 0.1.5 at time of writing this

**Comment by mkeedlinger** [comment]
Ok, upon further inspection I've found that you've fixed this problem: https://github.com/dotenv-rs/dotenv/commit/cfed2b85f4c8ed2816973200e8a228abfd45fdab

It's just not pushed as a version to crates.io

I'm going to leave this issue open to discuss a best way forward. For now I'm going to switch to Github in my `Cargo.toml`.

**Comment by SomeoneToIgnore** [comment]
Does `0.15.0` contain this fix?

**Comment by mkeedlinger** [comment]
I don't have access to an IDE right now, [but yes](https://docs.rs/dotenv/0.15.0/dotenv/enum.Error.html#implementations), it looks like `0.15.0` does indeed implement `std::error::Error`!

Thanks for the work that goes into this project!
