### ISSUE TITLE
Release for \n fix

### ISSUE THREAD

**Issue by liamdawson** [dotenv-rs/dotenv#28]
Hello! I opened a [bug report for a utility](https://github.com/casey/just/issues/468) I was using, which uses this library under the hood. Turns out there's a fix for the bug in question (#24), but it hasn't been released yet. Any chance the lovely maintainers could cut a new release with that fix? ❤️

**Comment by apiraino** [comment]
+1 for a new release.

I'd love to get rid of the `regex` dependency

**Comment by casey** [comment]
Hi @ZoeyR! Sorry to bug you, but would it be possible to cut a new release? (I'm also happy to do it, if you're comfortable giving me maintainer bits. I was a maintainer of the old git repo, although I don't think I ever had an owner bit on crates.io.)

**Comment by ZoeyR** [comment]
Published, sorry it took so long

**Comment by LasseBP** [comment]
Thanks for the new release 👍 Please tag, push that tag, and update the changelog
