### ISSUE TITLE
Un-deprecate `from_path_iter` or make `Iter` public

### ISSUE THREAD

**Issue by askoretskiy** [dotenv-rs/dotenv#43]
For my project I need a function that reads ENV file and do not change the current process environment.

I found out `dotenv::from_path_iter` is doing exactly what is needed. Unfortunately it is marked as deprecated and it is recommended to use `from_path` + `vars`.

The problem is that `from_path` updates the environment but I need just to read it, I would modify the env myself.

I could have used `Ok(Iter::new(File::open(path).map_err(Error::Io)?))` but `Iter` struct is private.

**Comment by Plecra** [comment]
Fyi, the deprecation warning has been removed

**Comment by askoretskiy** [comment]
Thank you @Plecra . Any plans for release?
