### ISSUE TITLE
Maintenance, state of release?

### ISSUE THREAD

**Issue by Veetaha** [dotenv-rs/dotenv#60]
Hey guys, what is the current status of this crate? There hasn't been a release to crates.io for 9 months. Are there any blockers for this? If you feel you don't have time/motivation to maintain this project, I'd suggest sharing the rights to push/publish the crate to some contributor

cc @ZoeyR , @purpliminal, @sgrif

**Comment by ghost** [comment]
I'm still trying to maintain this crate, I've just been sidetracked for a while due to life events/pandemic. Once I get some free time I'll work on a new release.
