### ISSUE TITLE
env::var vs dotenv::var 

### ISSUE THREAD

**Issue by DusterTheFirst** [dotenv-rs/dotenv#65]
What is the purpose of `dotenv::var` and `dotenv::vars` and how do they compare to their std::env equivalents

**Comment by DusterTheFirst** [comment]
upon looking into the code, it just calls std::env::var after first initializing dotenv. This should be made clearer in the documentation

**Comment by ghost** [comment]
The documentation for `dotenv::var` starts with the line "After loading the dotenv file, fetches the environment variable key from the current process. Is there anything that would make it clearer that it loads the file first and then fetches the variables?

**Comment by DusterTheFirst** [comment]
I guess I misunderstood the "After loading the dotenv file" to mean that this function must be called after `dotenv::dotenv`
